name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci_lint_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/golangci-lint.yml@18b498ec69917181b4cf83704f5bc5c56f77eacd
