name: Release Steampipe Anywhere Components

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: "The version to release (must be prefixed with 'v')"
        required: true

permissions:
  contents: write

jobs:
  anywhere_publish_workflow:
    uses: pluralsh/steampipe-workflows/.github/workflows/steampipe-anywhere-azure.yml@3fdeb9c4d7e6420b69362a799b949cd300cc5520
